apiVersion: v1
data:
  FIREBASE_API_KEY: AIzaSyASxKvIK2FYwsEHrhUKLTetfD4_TGteYpA
  FIREBASE_APP_ID: 1:836897641727:web:dd31648879f26ac09d68ca
  FIREBASE_AUTH_DOMAIN: fairshare-prod-82891.firebaseapp.com
  FIREBASE_MEASUREMENT_ID: G-9JL4R4X9R7
  FIREBASE_MESSAGING_SENDER_ID: "836897641727"
  FIREBASE_PROJECT_ID: fairshare-prod-82891
  FIREBASE_STORAGE_BUCKET: fairshare-prod-82891.firebasestorage.app
kind: ConfigMap
metadata:
  name: fairshare-client-config-9c466tdhd8
  namespace: prod
