apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: fairshare-prod
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Taku10/k3s-platform.git
    targetRevision: main
    path: apps/fairshare/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true