apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: fairshare-nonprod
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: fairshare:nonprod
  labels:
    app.kubernetes.io/name: fairshare
    app.kubernetes.io/instance: fairshare-nonprod
    app.kubernetes.io/part-of: fairshare
    platform.takunda.cloud/environment: nonprod
    platform.takunda.cloud/category: workload

spec:
  project: fairshare

  source:
    repoURL: https://github.com/Taku10/k3s-platform.git
    targetRevision: stage/nonprod
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: nonprod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
