apiVersion: v1
kind: Service
metadata:
  name: fruitku
  labels:
    app.kubernetes.io/name: fruitku
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: fruitku
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: fruitku
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
