apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/instance: portfolio-prod
    app.kubernetes.io/part-of: portfolio
    platform.takunda.cloud/environment: prod
    platform.takunda.cloud/category: workload
spec:
  project: portfolio
  source:
    repoURL: https://github.com/Taku10/k3s-platform.git
    targetRevision: main
    path: apps/portfolio/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
