apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - ingress.yaml

replicas:
  - name: portfolio
    count: 2

images:
  - name: ghcr.io/taku10/takunda-profile
    newTag: "95a03b71f7b5aa51141b697daa0a5ef57671bb82"
