apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: fairshare
  namespace: fairshare
spec:
  promotionPolicies:
    - stageSelector:
        name: nonprod
      autoPromotionEnabled: true
