apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairshare-client

spec:
  replicas: 2

  selector:
    matchLabels:
      app: fairshare-client

  template:
    metadata:
      labels:
        app: fairshare-client

    spec:
      containers:
        - name: fairshare-client
          image: ghcr.io/taku10/fairshare-client:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 80