apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base
  - ingress.yaml
  
configMapGenerator:
  - name: fairshare-client-config
    envs:
      - config.env
      
patches:
  - path: server-patch.yaml

images:
  - name: ghcr.io/taku10/fairshare-client
    newTag: "4867593"

  - name: ghcr.io/taku10/fairshare-server
    newTag: "4867593"