apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nonprod

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/taku10/fruitku
    newName: ghcr.io/taku10/fruitku
    digest: sha256:c8adf7d8d48d2eb52e6194f5b3c939924eeafb629fdd04a2952f8995c6d94d4a
