apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nonprod

resources:
  - ../../base
  - ingress.yaml

replicas:
  - name: portfolio
    count: 1

images:
  - name: ghcr.io/taku10/takunda-profile
    newTag: "c75220cb560a47140d0dbc5d6ae131cad0ae005b"
